### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by salvinramesh** [Crow08/discord-uberbot#87]
(node:2432) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at C:\Users\Salvin\Desktop\discord-uberbot\src\MusicClient.js:152:58
    at Map.forEach (<anonymous>)
    at MusicClient.ready (C:\Users\Salvin\Desktop\discord-uberbot\src\MusicClient.js:151:36)
    at Client.<anonymous> (C:\Users\Salvin\Desktop\discord-uberbot\src\index.js:116:19)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:467:12)
    at WebSocketShard.onPacket (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:439:16)
    at WebSocketShard.onMessage (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\ws\lib\websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\ws\lib\receiver.js:427:14)
    at Receiver.getData (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\ws\lib\receiver.js:366:17)
    at Receiver.startLoop (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\ws\lib\receiver.js:142:22)
    at Receiver._write (C:\Users\Salvin\Desktop\discord-uberbot\node_modules\ws\lib\receiver.js:77:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
(node:2432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by salvinramesh** [comment]
Help me please.. i really loved your project.

**Comment by MrShahan** [comment]
Hello my friend,

Thanks for your e-mail but i dont know make discord bots. I am sorry.


17 Eki 2020 Cmt 08:38 tarihinde salvinramesh <notifications@github.com>
şunu yazdı:
